name: diplomas

services:
  postgres:
    image: "postgres:16.3-alpine3.20"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: always

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}

  polls:
    build: ./polls
    ports:
      - 3000:3000
    depends_on:
      - postgres
    restart: always

  services:
    build: ./services
    ports:
      - 3001:3000
    depends_on:
      - postgres
      - minio
    restart: always
